# Basic
title: é½åˆ˜æµ·çš„å°æŸ´
subtitle: ä¸ªäººç«™
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Liming96
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: æ•°æ®åˆ†æ / ç»Ÿè®¡å­¦ä¹ 
url: "http://Liming96.io"

# Comment
comment:
    disqus: Liming96
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    github: Liming96
    # zhihu: panpanleopard
    # juejin: xxx
    # twitter: 
    mail: liming96@126.com

markdown: kramdown

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: xxxx  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: xxxx  
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

# ã€Š----------------- æ·»åŠ æ–‡ç« åˆ†ç±»åŠŸèƒ½ ---------------------------ã€‹

links1:
    - name:         æ‰€æœ‰
      url:          /
      type:         recent
      external:     false
    - name:         æœºå™¨å­¦ä¹ ç†è®º
      url:          /blog/mlelement
      type:         mlelement
      external:     false
    - name:         æœºå™¨å­¦ä¹ å®æˆ˜
      url:          /blog/mlaction
      type:         mlaction
      external:     /false
    - name:         å¤§æ•°æ®ç†è®º
      url:          /blog/bdelement
      type:         bdelement
      external:     false
    - name:         å¤§æ•°æ®å®æˆ˜
      url:          /blog/bdaction
      type:         bdaction
      external:     false
    - name:         ç»Ÿè®¡å­¦
      url:          /blog/statistics
      type:         statistics
      external:     false
blog_1:     recent
blog_2:     mlelement
blog_3:     mlaction
blog_4:     bdelement
blog_5:     bdaction
blog_6:     statistics






